<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Product View</title>
</head>

<body>
    <!--Main Navigation-->
    <header>
        <!-- Jumbotron -->
        <div class="p-3 text-center bg-white border-bottom">
            <div class="container">
                <div class="row gy-3">
                    <!-- Left elements -->
                    <div class="col-lg-2 col-sm-4 col-4">
                        <b style="font-size: 2em; margin-right: 30px; color:blue">Music Box</b>
                    </div>
                    <!-- Left elements -->

                    <!-- Center elements -->
                    <div class="order-lg-last col-lg-10 col-sm-8 col-8">
                        <div class="d-flex float-end">
                            <a href="/" class="me-1 border rounded py-1 px-3 nav-link d-flex align-items-center">
                                <i class="fas fa-shopping-cart m-1 me-md-2"></i>
                                <p class="d-none d-md-block mb-0">Search</p>
                            </a>
                            <a href="/display" class="me-1 border rounded py-1 px-3 nav-link d-flex align-items-center">
                                <i class="fas fa-shopping-cart m-1 me-md-2"></i>
                                <p class="d-none d-md-block mb-0">Home</p>
                            </a>
                            <a href="/data" class="me-1 border rounded py-1 px-3 nav-link d-flex align-items-center">
                                <i class="fas fa-shopping-cart m-1 me-md-2"></i>
                                <p class="d-none d-md-block mb-0">My Saves</p>
                            </a>
                        </div>
                    </div>
                    <!-- Center elements -->

                    <!-- Right elements -->
                </div>
            </div>
        </div>
        <!-- Jumbotron -->

        <!-- Navbar -->
        <!-- Jumbotron -->
        <div class="bg-primary text-white py-5">
            <div class="container py-5">
                <h1>
                    Best Music & <br />
                    Podcast in our store
                </h1>
                <p>Trendy Album, Songs, Audibooks Avilable</p>
            </div>
        </div>
        <!-- Jumbotron -->
    </header>

    <!-- Products -->
    <section>
        <div class="container my-5">
            <header class="mb-4">
                <h3>Searched Result</h3>
            </header>
            <div class="row" id="main_display">
                <?php
                echo $album;
                ?>
                <?php
                echo $artist;
                ?>
                <?php
                echo $playlist;
                ?>
                <?php
                echo $track;
                ?>
                <?php
                echo $show;
                ?>
                <?php
                echo $episode;
                ?>
            </div>
        </div>
    </section>
    <!-- Products -->

</body>
<!-- Custom scripts -->
<script type="text/javascript" src="./JS/script.js"></script>

</html>